# -*- coding: utf-8 -*-
"""Average_Aggregate_row.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dyQ9plurfsrb6jRypg_gGMUGIZdmEzKA

The file contains gene names in rows and sample ID in column. for genes, there are total 174596 rows which include empty rows(undefined gene name) and duplicate gene names. Our objective is to combine multiple rows belonging to same gene and taking its mean. 
the input file: **GSE178967_ZR_NA_col1gene.xlsx** is pre-processed in following ways:
1. Sum of each gene  from all samples with value less than 10 expression are removed
2. gene rows with empty name renamed as NA using bash script.
3. The NA values are not removed in this file but as we wont continue with the NA rows, we will remove the aggregated NA from the output file after aggregate function.
"""

## input object created for the file GSE178967_ZR_NA_col1gene.xlsx with samples in column and genes are in rows
input <- read.table("/content/GSE178967_ZR_NA_col1gene.txt",header=T,sep="\t")

dim(input)

head(input)

#agrregate=aggregate(. ~ id, data = input, mean) 
## id is header name of row which have duplicates, please change according to your file column name. here "gene"

agrregate=aggregate(. ~ gene, data = input, mean) 

#convert into a data frame
agrregate<-data.frame(agrregate)

head(agrregate)

dim(agrregate)

write.table(data.frame('ID'=rownames(agrregate), agrregate),file="Aggregate_data.txt",sep='\t',quote = F,row.names = FALSE)

"""the Aggregate_data.txt is used as input file for PCA and DESEQ2 preprocessing. but before that NA rows need to removed but the output file of aggregate function didnt had NA rows. 
possible reason: Aggregate function might have removed NA automatically or there might be error. so to confirm this, we rerun the code block with the input file in which all NA entries in 1st column (gene) were replaced with NA1. the new input file is: 
"""

## input object created for the file GSE178967_ZR_NA_col1gene1_NA_1.TXT with samples in column and genes are in rows
input <- read.table("/content/GSE178967_ZR_NA_col1gene1_NA_1.txt",header=T,sep="\t")

dim(input)

head(input)

#agrregate=aggregate(. ~ id, data = input, mean) 
## id is header name of row which have duplicates, please change according to your file column name. here "gene"

aggregate=aggregate(. ~ gene, data = input, mean) 

#convert into a data frame
aggregate<-data.frame(aggregate)

head(aggregate)

dim(aggregate)

"""the dimension of previous formula was 34560 181. here we have 34561 i.e., one additional row for NA1. After downloading now we can remove NA1 and proceed with PCA and DESEQ2. but we will proceed with Aggregate_data.txt file. """

write.table(data.frame('ID'=rownames(aggregate), aggregate),file="GSE178967_Aggregate_data.txt",sep='\t',quote = F,row.names = FALSE)